### ISSUE TITLE
Prefer function .name to overwriting Symbol

### ISSUE THREAD

**Issue by bakkot** [es-shims/Symbol.prototype.description#1]
```js
let empty = Symbol('');
let undef = Symbol();
console.log(
  {[empty](){}}[empty].name === '[]', // true
  {[undef](){}}[undef].name === '', // true
);
```

Except this only works on browsers where function name inference works correctly for symbol-named functions, which in my tests includes Chrome and FF but not Safari.

**Comment by ljharb** [comment]
I can totally detect this in the browsers that support both Symbols and concise method syntax and function name inference; but I'll still need to keep the `Symbol` replacement for the rest :-/
